# Generated by Django 5.1.6 on 2026-01-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_details',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crop_details',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crop_details',
            name='soil_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='rainfall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crop_details',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fert_details',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
